name: generate animation

on:
  watch:
    types: [started]
  # run automatically every 24 hours
  schedule:
    - cron: "0 16 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Download svg
        uses: actions/checkout@v3
        with:
          ref: output

      - name: Upload to OSS
        env:
          OSS_AccessKeyID: ${{ secrets.OSS_AccessKeyID }}
          OSS_AccessKeySecret: ${{ secrets.OSS_AccessKeySecret }}
        run: |
          wget -q https://gosspublic.alicdn.com/ossutil/1.7.15/ossutil64
          chmod +x ./ossutil64
          ./ossutil64 config -e oss-cn-shanghai.aliyuncs.com -i $OSS_AccessKeyID -k $OSS_AccessKeySecret -L CH
          echo y | ./ossutil64 rm oss://hutu2/github -r
          ./ossutil64 cp github-contribution-grid-snake.svg oss://hutu2/github/
          ./ossutil64 cp github-contribution-grid-snake-dark.svg oss://hutu2/github/